export const dum = {
  _lstBillItems: [
    {
      ID: 0,
      BillID: 0,
      BillNo: "",
      TestID: 0,
      billDGid: 0,
      billTestName: item name,
      billPrice: rate,
      billOutGoing: true,
      billDiscount: percent calculate,
      billDiscountAmt: amount discount,
      billPriceFinal: grand total,
      IsSync: true,
      RoundAmt: round amount,
      Remarks: "",
      OutgoingLabId: 1,
    },
  ],
  Id: 0,
  PatId: 2,
  Nrl_Reg_No: "sample string 3",
  TestId: 0,
  Price: sub total,
  TotalPrice: grand total,
  DiscountPrice: discount amount,
  HSTPrice: 0,
  IsPaid: true,
  IsDone: true,
  BillDate: date object '2022-10-12T',
//   BillLastModifiedDate: date object '2022-10-12T',
  BillLastModifiedDate:date: {'2022-10-12T'},
  BillNo: "",
  BillDiscount: bill percent,
  BillDiscountAmt: bill discount amount,
  BillHst: 0,
  BillHstAmt: 0,
  BillAmtPaid: grand total,
  BillRemainingAmt: 0,
  BillPaymentType: payment type,
  BillOutGngAmt: grand total,
  BillOutGngDiscountAmt: bill discount amount,
  BillOutGngAmtPc: 1,
  UserId: 1,
  BillIsVoid: false,
  BillLastModifiedUser: 1,
  BillAdvanceAmt: 0,
  BillCollectionAmt: grand total,
  BillNepaliDate: "",
  BillLastModifiedNepaliDate: "",
  BillRoundedAmt: rounded amount,
  BillWithoutRound: sub total,
  BillCreditPartyCode: code,
  BillPassword: "",
  IsSync: true,
  PaymentMode: "Cash",
  Remarks: "",
  PaymentCode: "",
  SampleId: 0,
  FiscalYearId: 1,
};
