export const dum = {
    "_lstBillItems": [
        {
            "ID": 1,
            "BillID": 2,
            "BillNo": "sample string 3",
            "TestID": 4,
            "billDGid": 5,
            "billTestName": "sample string 6",
            "billPrice": 7.0,
            "billOutGoing": true,
            "billDiscount": 9.0,
            "billDiscountAmt": 10.0,
            "billPriceFinal": 11.0,
            "IsSync": true,
            "RoundAmt": 13.0,
            "Remarks": "sample string 14",
            "OutgoingLabId": 15
        },
        {
            "ID": 1,
            "BillID": 2,
            "BillNo": "sample string 3",
            "TestID": 4,
            "billDGid": 5,
            "billTestName": "sample string 6",
            "billPrice": 7.0,
            "billOutGoing": true,
            "billDiscount": 9.0,
            "billDiscountAmt": 10.0,
            "billPriceFinal": 11.0,
            "IsSync": true,
            "RoundAmt": 13.0,
            "Remarks": "sample string 14",
            "OutgoingLabId": 15
        },
        {
            "ID": 1,
            "BillID": 2,
            "BillNo": "sample string 3",
            "TestID": 4,
            "billDGid": 5,
            "billTestName": "sample string 6",
            "billPrice": 7.0,
            "billOutGoing": true,
            "billDiscount": 9.0,
            "billDiscountAmt": 10.0,
            "billPriceFinal": 11.0,
            "IsSync": true,
            "RoundAmt": 13.0,
            "Remarks": "sample string 14",
            "OutgoingLabId": 15
        }
    ],
    "Id": 1,
    "PatId": 2,
    "Nrl_Reg_No": "sample string 3",
    "TestId": 4,
    "Price": 5.0,
    "TotalPrice": 6.0,
    "DiscountPrice": 7.0,
    "HSTPrice": 8.0,
    "IsPaid": true,
    "IsDone": true,
    "BillDate": "2022-10-20T15:59:46.9371528+05:45",
    "BillLastModifiedDate": "2022-10-20T15:59:46.9371528+05:45",
    "BillNo": "A",
    "BillDiscount": 14.1,
    "BillDiscountAmt": 15.0,
    "BillHst": 16,
    "BillHstAmt": 17.0,
    "BillAmtPaid": 18.0,
    "BillRemainingAmt": 19.0,
    "BillPaymentType": "sample string 20",
    "BillOutGngAmt": 21.0,
    "BillOutGngDiscountAmt": 22.0,
    "BillOutGngAmtPc": 23,
    "UserId": 24,
    "BillIsVoid": true,
    "BillLastModifiedUser": 26,
    "BillAdvanceAmt": 27.0,
    "BillCollectionAmt": 28.0,
    "BillNepaliDate": "sample string 29",
    "BillLastModifiedNepaliDate": "sample string 30",
    "BillRoundedAmt": "sample string 31",
    "BillWithoutRound": "sample string 32",
    "BillCreditPartyCode": "sample string 33",
    "BillPassword": "sample string 34",
    "IsSync": true,
    "PaymentMode": "sample string 36",
    "Remarks": "sample string 37",
    "PaymentCode": "sample string 38",
    "SampleId": 39,
    "FiscalYearId": 40
}